package com.lianshengtong.gateway.gray;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.lianshengtong.gateway.gray.spi.InMemoryGrayPolicyRepository;
import com.lianshengtong.gateway.gray.spi.JdbcGrayPolicyRepository;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.embedded.EmbeddedDatabase;
import org.springframework.jdbc.datasource.embedded.EmbeddedDatabaseBuilder;
import org.springframework.jdbc.datasource.embedded.EmbeddedDatabaseType;

import java.time.Instant;
import java.util.List;
import java.util.Map;
import java.util.Optional;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Phase I：持久化层对比测试
 *  - InMemory 兜底：接口行为契约
 *  - JDBC（H2 模拟）：loadAll/save/findById/delete/appendHistory/listHistory 端到端
 */
class GrayPolicyRepositoryContractTest {

    JdbcGrayPolicyRepository jdbc;
    InMemoryGrayPolicyRepository mem;
    EmbeddedDatabase db;

    @BeforeEach void setUp() {
        db = new EmbeddedDatabaseBuilder()
                .setType(EmbeddedDatabaseType.H2)
                .setName("gray_" + System.nanoTime()) // 每方法独立 DB，避免跨测例污染
                .build();
        initH2Schema(db);
        jdbc = new JdbcGrayPolicyRepository(new JdbcTemplate(db), new ObjectMapper());
        mem = new InMemoryGrayPolicyRepository();
    }

    @AfterEach void tearDown() {
        if (db != null) db.shutdown();
    }

    static void initH2Schema(EmbeddedDatabase db) {
        JdbcTemplate j = new JdbcTemplate(db);
        j.execute("CREATE TABLE IF NOT EXISTS gray_policy (" +
                " policy_id VARCHAR(128) PRIMARY KEY," +
                " route_id VARCHAR(128) NOT NULL," +
                " baseline_uri VARCHAR(255) NOT NULL," +
                " canary_uri VARCHAR(255) NOT NULL," +
                " canary_weight_percent INT NOT NULL," +
                " rules_json TEXT NULL," +
                " meta_json TEXT NULL," +
                " status VARCHAR(16) NOT NULL," +
                " created_at TIMESTAMP NOT NULL," +
                " updated_at TIMESTAMP NOT NULL," +
                " updated_by VARCHAR(64) NULL)");
        j.execute("CREATE TABLE IF NOT EXISTS gray_policy_history (" +
                " id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
                " ts TIMESTAMP NOT NULL," +
                " policy_id VARCHAR(128) NULL," +
                " operator VARCHAR(64) NOT NULL," +
                " action VARCHAR(32) NOT NULL," +
                " detail VARCHAR(1024) NULL)");
    }

    GrayPolicyStore.Policy sample(String id, int w, GrayPolicyStore.Status s) {
        return GrayPolicyStore.Policy.legacy(id, "route-"+id,
                "lb://svc","lb://svc-canary", w,
                List.of(new GrayPolicyStore.Rule("HEADER","X-Canary","EQ","force",null)),
                Map.of("owner","ops"), s, Instant.now(), Instant.now(), "junit");
    }

    // ---- InMemory 契约 ----
    @Test @DisplayName("InMemory: loadAll / save / findById / delete")
    void inMemoryCrud() {
        assertThat(mem.isAvailable()).isTrue();
        mem.save(sample("a", 10, GrayPolicyStore.Status.ACTIVE));
        assertThat(mem.findById("a")).isPresent().get().extracting(GrayPolicyStore.Policy::policyId).isEqualTo("a");
        assertThat(mem.loadAll()).hasSize(1);
        mem.delete("a");
        assertThat(mem.findById("a")).isEmpty();
    }

    @Test @DisplayName("InMemory: appendHistory + listHistory 全局/按策略 + 排序（新→旧）")
    void inMemoryHistory() {
        Instant t1 = Instant.now();
        mem.appendHistory(new GrayPolicyStore.History(t1, "p1", "ops", "CREATE", "1"));
        mem.appendHistory(new GrayPolicyStore.History(t1.plusSeconds(1), "p2", "ops", "WEIGHT_CHANGE", "2"));
        mem.appendHistory(new GrayPolicyStore.History(t1.plusSeconds(2), "p1", "ops", "ROLLBACK", "3"));
        assertThat(mem.listHistory("p1", 10)).extracting(GrayPolicyStore.History::detail)
                .containsExactly("3", "1");
        assertThat(mem.listHistory(null, 10)).extracting(GrayPolicyStore.History::action)
                .containsExactly("ROLLBACK", "WEIGHT_CHANGE", "CREATE");
    }

    // ---- JDBC (H2) ----
    @Test @DisplayName("JDBC: save + findById + loadAll + delete")
    void jdbcCrud() {
        GrayPolicyStore.Policy a = sample("a-jdbc", 20, GrayPolicyStore.Status.ACTIVE);
        jdbc.save(a);
        Optional<GrayPolicyStore.Policy> read = jdbc.findById("a-jdbc");
        assertThat(read).isPresent();
        assertThat(read.get().routeId()).isEqualTo("route-a-jdbc");
        assertThat(read.get().rules()).hasSize(1);
        assertThat(read.get().rules().get(0).key()).isEqualTo("X-Canary");
        assertThat(read.get().meta()).containsEntry("owner", "ops");
        assertThat(read.get().status()).isEqualTo(GrayPolicyStore.Status.ACTIVE);
        assertThat(read.get().canaryWeightPercent()).isEqualTo(20);

        GrayPolicyStore.Policy b = sample("b-jdbc", 0, GrayPolicyStore.Status.PAUSED);
        jdbc.save(b);
        assertThat(jdbc.loadAll()).hasSize(2);
        jdbc.delete("a-jdbc");
        assertThat(jdbc.findById("a-jdbc")).isEmpty();
        assertThat(jdbc.loadAll()).hasSize(1);
    }

    @Test @DisplayName("JDBC: upsert（H2 fallback UPDATE then INSERT） 正确覆盖")
    void jdbcUpsertOverwrite() {
        GrayPolicyStore.Policy v1 = sample("u", 10, GrayPolicyStore.Status.ACTIVE);
        jdbc.save(v1);
        GrayPolicyStore.Policy v2 = GrayPolicyStore.Policy.legacy("u", "route-u",
                v1.baselineUri(), v1.canaryUri(), 80,
                List.of(), Map.of("owner","new-owner"), GrayPolicyStore.Status.PAUSED,
                v1.createdAt(), Instant.now(), "junit2");
        jdbc.save(v2);
        GrayPolicyStore.Policy read = jdbc.findById("u").orElseThrow();
        assertThat(read.canaryWeightPercent()).isEqualTo(80);
        assertThat(read.status()).isEqualTo(GrayPolicyStore.Status.PAUSED);
        assertThat(read.rules()).isEmpty();
        assertThat(read.meta()).containsEntry("owner", "new-owner");
        assertThat(read.updatedBy()).isEqualTo("junit2");
    }

    @Test @DisplayName("JDBC: appendHistory + listHistory(按 policyId / 全局)")
    void jdbcHistory() {
        Instant t0 = Instant.now();
        jdbc.appendHistory(new GrayPolicyStore.History(t0, "p", "o1", "CREATE", "first"));
        jdbc.appendHistory(new GrayPolicyStore.History(t0.plusSeconds(1), "q", "o2", "WEIGHT_CHANGE", "second"));
        jdbc.appendHistory(new GrayPolicyStore.History(t0.plusSeconds(2), "p", "o1", "ROLLBACK", "third"));
        List<GrayPolicyStore.History> pHist = jdbc.listHistory("p", 10);
        assertThat(pHist).extracting(GrayPolicyStore.History::detail).containsExactly("third", "first");

        List<GrayPolicyStore.History> all = jdbc.listHistory(null, 10);
        assertThat(all).extracting(GrayPolicyStore.History::action).containsExactly("ROLLBACK", "WEIGHT_CHANGE", "CREATE");
    }

    @Test @DisplayName("JDBC: loadAll 返回空集合时不应异常")
    void jdbcLoadEmpty() {
        assertThat(jdbc.loadAll()).isEmpty();
    }
}
