package com.lianshengtong.user.service.impl;

import com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper;
import com.baomidou.mybatisplus.core.conditions.update.LambdaUpdateWrapper;
import com.baomidou.mybatisplus.core.metadata.TableInfoHelper;
import com.baomidou.mybatisplus.extension.plugins.pagination.Page;
import com.baomidou.mybatisplus.core.metadata.IPage;
import com.baomidou.mybatisplus.session.Configuration;
import com.baomidou.mybatisplus.builder.MapperBuilderAssistant;
import com.lianshengtong.common.enums.MerchantPenaltyStatusEnum;
import com.lianshengtong.common.enums.UserTypeEnum;
import com.lianshengtong.common.exception.BizException;
import com.lianshengtong.common.result.ResultCode;
import com.lianshengtong.user.dto.LoginDTO;
import com.lianshengtong.user.dto.MerchantApplyDTO;
import com.lianshengtong.user.dto.RegisterDTO;
import com.lianshengtong.user.dto.VerifyDTO;
import com.lianshengtong.user.entity.MerchantExtension;
import com.lianshengtong.user.entity.StoreAddress;
import com.lianshengtong.user.entity.User;
import com.lianshengtong.user.mapper.MerchantExtensionMapper;
import com.lianshengtong.user.mapper.StoreAddressMapper;
import com.lianshengtong.user.mapper.UserMapper;
import com.lianshengtong.user.util.JwtUtil;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.data.redis.core.StringRedisTemplate;
import org.springframework.data.redis.core.ValueOperations;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
import org.springframework.test.util.ReflectionTestUtils;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.*;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
@DisplayName("用户与商家服务边界用例测试")
class UserEdgeCaseTest {

    @BeforeAll
    static void initTableInfo() {
        MapperBuilderAssistant assistant = new MapperBuilderAssistant(new Configuration(), "");
        TableInfoHelper.initTableInfo(assistant, MerchantExtension.class);
        TableInfoHelper.initTableInfo(assistant, StoreAddress.class);
    }

    @Nested
    @DisplayName("UserServiceImpl 边界测试")
    class UserServiceEdgeTests {

        @Mock
        private UserMapper userMapper;
        @Mock
        private JwtUtil jwtUtil;

        @InjectMocks
        private UserServiceImpl userService;

        private final BCryptPasswordEncoder passwordEncoder = new BCryptPasswordEncoder();

        @BeforeEach
        void setUp() {
            ReflectionTestUtils.setField(userService, "aesRawKey", "LscIdCardAesKey2026!!");
            ReflectionTestUtils.invokeMethod(userService, "initAesKey");
        }

        @Test
        @DisplayName("register: 用户类型为null时默认为消费者")
        void register_nullUserType_defaultsToConsumer() {
            RegisterDTO dto = new RegisterDTO();
            dto.setMobile("13800138000");
            dto.setPassword("test123456");
            dto.setUserType(null);

            when(userMapper.selectCount(any(LambdaQueryWrapper.class))).thenReturn(0L);
            when(userMapper.insert(any(User.class))).thenReturn(1);

            User result = userService.register(dto);
            assertEquals(UserTypeEnum.CONSUMER.getCode(), result.getUserType());
        }

        @Test
        @DisplayName("register: 昵称为空时自动生成默认昵称")
        void register_nullNickname_autoGenerated() {
            RegisterDTO dto = new RegisterDTO();
            dto.setMobile("13800138000");
            dto.setPassword("test123456");
            dto.setNickname(null);

            when(userMapper.selectCount(any(LambdaQueryWrapper.class))).thenReturn(0L);
            when(userMapper.insert(any(User.class))).thenReturn(1);

            User result = userService.register(dto);
            assertNotNull(result.getNickname());
        }

        @Test
        @DisplayName("register: 推荐码用userId作为默认值")
        void register_referralCodeEqualsUserId() {
            RegisterDTO dto = new RegisterDTO();
            dto.setMobile("13800138000");
            dto.setPassword("test123456");
            dto.setUserType(0);

            when(userMapper.selectCount(any(LambdaQueryWrapper.class))).thenReturn(0L);
            when(userMapper.insert(any(User.class))).thenAnswer(invocation -> {
                User u = invocation.getArgument(0);
                assertEquals(String.valueOf(u.getUserId()), u.getReferralCode());
                return 1;
            });

            userService.register(dto);
        }

        @Test
        @DisplayName("login: 状态为null视为正常状态")
        void login_nullStatus_treatedAsActive() {
            LoginDTO dto = new LoginDTO();
            dto.setAccount("13800138000");
            dto.setPassword("test123456");

            User user = new User();
            user.setUserId(1L);
            user.setMobile("13800138000");
            user.setPasswordHash(passwordEncoder.encode("test123456"));
            user.setStatus(null);

            when(userMapper.selectOne(any(LambdaQueryWrapper.class))).thenReturn(user);
            when(jwtUtil.generateToken(anyString(), anyString(), any())).thenReturn("token");

            String token = userService.login(dto);
            assertEquals("token", token);
        }

        @Test
        @DisplayName("changePassword: 新密码为空抛异常")
        void changePassword_emptyNewPassword_throws() {
            User user = new User();
            user.setUserId(1L);
            user.setPasswordHash(passwordEncoder.encode("oldpass"));

            when(userMapper.selectById(1L)).thenReturn(user);

            BizException ex = assertThrows(BizException.class,
                    () -> userService.changePassword(1L, "oldpass", ""));
            assertEquals(400, ex.getCode());
        }

        @Test
        @DisplayName("changePassword: 新密码短于6位抛异常")
        void changePassword_shortNewPassword_throws() {
            User user = new User();
            user.setUserId(1L);
            user.setPasswordHash(passwordEncoder.encode("oldpass"));

            when(userMapper.selectById(1L)).thenReturn(user);

            BizException ex = assertThrows(BizException.class,
                    () -> userService.changePassword(1L, "oldpass", "12345"));
            assertEquals(400, ex.getCode());
        }

        @Test
        @DisplayName("changePassword: 用户不存在抛异常")
        void changePassword_userNotFound_throws() {
            when(userMapper.selectById(999L)).thenReturn(null);

            BizException ex = assertThrows(BizException.class,
                    () -> userService.changePassword(999L, "old", "newpass123"));
            assertEquals(404, ex.getCode());
        }

        @Test
        @DisplayName("verify: 用户不存在抛异常")
        void verify_userNotFound_throws() {
            VerifyDTO dto = new VerifyDTO();
            dto.setUserId(999L);
            dto.setRealName("张");
            dto.setIdCardNo("110101199003071234");

            when(userMapper.selectById(999L)).thenReturn(null);

            BizException ex = assertThrows(BizException.class, () -> userService.verify(dto));
            assertEquals(404, ex.getCode());
        }

        @Test
        @DisplayName("getUserInfo: 成功获取并脱敏")
        void getUserInfo_success_masked() {
            User user = new User();
            user.setUserId(1L);
            user.setMobile("13800138000");
            user.setNickname("用户1");
            user.setPasswordHash("hashed_value");
            user.setStatus(1);

            when(userMapper.selectById(1L)).thenReturn(user);

            User result = userService.getUserInfo(1L);
            assertNotNull(result);
            assertNull(result.getPasswordHash());
        }

        @Test
        @DisplayName("register: 用户类型为商家时正确设置")
        void register_merchantType() {
            RegisterDTO dto = new RegisterDTO();
            dto.setMobile("13900139000");
            dto.setPassword("test123456");
            dto.setUserType(UserTypeEnum.MERCHANT.getCode());

            when(userMapper.selectCount(any(LambdaQueryWrapper.class))).thenReturn(0L);
            when(userMapper.insert(any(User.class))).thenReturn(1);

            User result = userService.register(dto);
            assertEquals(UserTypeEnum.MERCHANT.getCode(), result.getUserType());
        }
    }

    @Nested
    @DisplayName("MerchantServiceImpl 边界测试")
    class MerchantServiceEdgeTests {

        @Mock
        private MerchantExtensionMapper merchantMapper;
        @Mock
        private StoreAddressMapper storeAddressMapper;
        @Mock
        private StringRedisTemplate stringRedisTemplate;
        @Mock
        private ValueOperations<String, String> valueOperations;

        @InjectMocks
        private MerchantServiceImpl merchantService;

        private MerchantExtension buildExtension(Long merchantId) {
            MerchantExtension ext = new MerchantExtension();
            ext.setMerchantId(merchantId);
            ext.setStoreName("测试店铺");
            ext.setBusinessLicense("91330100MA2XXXXXXX");
            ext.setCreditScore(100);
            ext.setAiRiskScore(100);
            ext.setDailyNhLimit(80);
            ext.setNhLimitLevel(0);
            ext.setPenaltyStatus(MerchantPenaltyStatusEnum.NORMAL.getCode());
            ext.setAuditStatus(0);
            ext.setAddressUpdateCount(0);
            ext.setProvince("浙江省");
            ext.setCity("杭州市");
            ext.setDistrict("西湖区");
            ext.setAddressDetail("文三路100号");
            ext.setContactPhone("13800138000");
            ext.setBusinessHours("09:00-22:00");
            return ext;
        }

        private MerchantApplyDTO buildDTO(Long merchantId) {
            MerchantApplyDTO dto = new MerchantApplyDTO();
            dto.setMerchantId(merchantId);
            dto.setBusinessLicense("91330100MA2XXXXXXX");
            dto.setBusinessLicenseImg("https://img.example.com/lic.jpg");
            dto.setStoreName("测试店铺");
            dto.setProvince("浙江省");
            dto.setCity("杭州市");
            dto.setDistrict("西湖区");
            dto.setAddressDetail("文三路100号");
            dto.setContactPhone("13800138000");
            dto.setBusinessHours("09:00-22:00");
            return dto;
        }

        private void mockRedisIncrement(Long count) {
            when(stringRedisTemplate.opsForValue()).thenReturn(valueOperations);
            when(valueOperations.increment(anyString())).thenReturn(count);
        }

        @Test
        @DisplayName("audit: 审核状态为null抛异常")
        void audit_nullStatus_throws() {
            assertThrows(BizException.class,
                    () -> merchantService.audit(1L, null, "test"));
        }

        @Test
        @DisplayName("audit: 非法审核状态(3)抛异常")
        void audit_invalidStatus3_throws() {
            assertThrows(BizException.class,
                    () -> merchantService.audit(1L, 3, "test"));
        }

        @Test
        @DisplayName("audit: 非法审核状态(0)抛异常")
        void audit_invalidStatus0_throws() {
            assertThrows(BizException.class,
                    () -> merchantService.audit(1L, 0, "test"));
        }

        @Test
        @DisplayName("updateCredit: creditScore为null抛异常")
        void updateCredit_nullScore_throws() {
            assertThrows(BizException.class,
                    () -> merchantService.updateCredit(1L, null));
        }

        @Test
        @DisplayName("updateCredit: creditScore为负数抛异常")
        void updateCredit_negativeScore_throws() {
            assertThrows(BizException.class,
                    () -> merchantService.updateCredit(1L, -1));
        }

        @Test
        @DisplayName("updateCredit: creditScore超过100抛异常")
        void updateCredit_over100_throws() {
            assertThrows(BizException.class,
                    () -> merchantService.updateCredit(1L, 101));
        }

        @Test
        @DisplayName("updateCredit: 信用分100为正常状态")
        void updateCredit_score100_normal() {
            MerchantExtension ext = buildExtension(1L);
            when(merchantMapper.selectById(1L)).thenReturn(ext);
            when(merchantMapper.updateById(any(MerchantExtension.class))).thenReturn(1);

            MerchantExtension result = merchantService.updateCredit(1L, 100);
            assertEquals(MerchantPenaltyStatusEnum.NORMAL.getCode(), result.getPenaltyStatus());
        }

        @Test
        @DisplayName("updateCredit: 信用分20-39为三级处罚")
        void updateCredit_score30_level3() {
            MerchantExtension ext = buildExtension(1L);
            when(merchantMapper.selectById(1L)).thenReturn(ext);
            when(merchantMapper.updateById(any(MerchantExtension.class))).thenReturn(1);

            MerchantExtension result = merchantService.updateCredit(1L, 30);
            assertEquals(MerchantPenaltyStatusEnum.LEVEL3.getCode(), result.getPenaltyStatus());
        }

        @Test
        @DisplayName("updateCredit: 信用分0为清退状态")
        void updateCredit_score0_expelled() {
            MerchantExtension ext = buildExtension(1L);
            when(merchantMapper.selectById(1L)).thenReturn(ext);
            when(merchantMapper.updateById(any(MerchantExtension.class))).thenReturn(1);

            MerchantExtension result = merchantService.updateCredit(1L, 0);
            assertEquals(MerchantPenaltyStatusEnum.EXPELLED.getCode(), result.getPenaltyStatus());
        }

        @Test
        @DisplayName("updateWriteOffLevel: level为null抛异常")
        void updateWriteOffLevel_nullLevel_throws() {
            assertThrows(BizException.class,
                    () -> merchantService.updateWriteOffLevel(1L, null));
        }

        @Test
        @DisplayName("updateWriteOffLevel: level超过16抛异常")
        void updateWriteOffLevel_over16_throws() {
            assertThrows(BizException.class,
                    () -> merchantService.updateWriteOffLevel(1L, 17));
        }

        @Test
        @DisplayName("updateWriteOffLevel: level为负数抛异常")
        void updateWriteOffLevel_negative_throws() {
            assertThrows(BizException.class,
                    () -> merchantService.updateWriteOffLevel(1L, -1));
        }

        @Test
        @DisplayName("penalize: penaltyType为null抛异常")
        void penalize_nullType_throws() {
            assertThrows(BizException.class,
                    () -> merchantService.penalize(1L, null, "reason", null));
        }

        @Test
        @DisplayName("penalize: penaltyType超过4抛异常")
        void penalize_over4_throws() {
            assertThrows(BizException.class,
                    () -> merchantService.penalize(1L, 5, "reason", null));
        }

        @Test
        @DisplayName("penalize: 二级处罚扣20分")
        void penalize_level2_deduct20() {
            MerchantExtension ext = buildExtension(1L);
            ext.setCreditScore(90);
            when(merchantMapper.selectById(1L)).thenReturn(ext);
            when(merchantMapper.updateById(any(MerchantExtension.class))).thenReturn(1);

            MerchantExtension result = merchantService.penalize(1L, 2, "违规", null);
            assertEquals(70, result.getCreditScore());
            assertEquals(2, result.getPenaltyStatus());
        }

        @Test
        @DisplayName("penalize: level为0时不扣分")
        void penalize_level0_noDeduct() {
            MerchantExtension ext = buildExtension(1L);
            ext.setCreditScore(50);
            when(merchantMapper.selectById(1L)).thenReturn(ext);
            when(merchantMapper.updateById(any(MerchantExtension.class))).thenReturn(1);

            MerchantExtension result = merchantService.penalize(1L, 0, "警告", null);
            assertEquals(50, result.getCreditScore());
        }

        @Test
        @DisplayName("adjustCredit: delta为null抛异常")
        void adjustCredit_nullDelta_throws() {
            assertThrows(BizException.class,
                    () -> merchantService.adjustCredit(1L, null, "reason"));
        }

        @Test
        @DisplayName("adjustCredit: 信用分低至0以下被限制在0")
        void adjustCredit_clampTo0() {
            MerchantExtension ext = buildExtension(1L);
            ext.setCreditScore(5);
            when(merchantMapper.selectById(1L)).thenReturn(ext);
            when(merchantMapper.updateById(any(MerchantExtension.class))).thenReturn(1);

            MerchantExtension result = merchantService.adjustCredit(1L, -10, "扣分");
            assertEquals(0, result.getCreditScore());
        }

        @Test
        @DisplayName("updateStoreInfo: 空Map参数抛异常")
        void updateStoreInfo_emptyMap_throws() {
            assertThrows(BizException.class,
                    () -> merchantService.updateStoreInfo(1L, new HashMap<>()));
        }

        @Test
        @DisplayName("updateStoreInfo: null参数抛异常")
        void updateStoreInfo_nullParam_throws() {
            assertThrows(BizException.class,
                    () -> merchantService.updateStoreInfo(1L, null));
        }

        @Test
        @DisplayName("getCreditDetail: 信用分为null时使用默认值")
        void getCreditDetail_nullScore_default0() {
            MerchantExtension ext = buildExtension(1L);
            ext.setCreditScore(null);
            when(merchantMapper.selectById(1L)).thenReturn(ext);

            Map<String, Object> result = merchantService.getCreditDetail(1L);
            assertEquals(0, result.get("creditScore"));
        }

        @Test
        @DisplayName("saveStoreAddress: merchantId为null抛异常")
        void saveStoreAddress_nullMerchantId_throws() {
            StoreAddress addr = new StoreAddress();
            assertThrows(BizException.class,
                    () -> merchantService.saveStoreAddress(addr));
        }

        @Test
        @DisplayName("saveStoreAddress: 编辑时非本商家地址抛FORBIDDEN")
        void saveStoreAddress_editWrongMerchant_throws() {
            MerchantExtension ext = buildExtension(1L);
            when(merchantMapper.selectById(1L)).thenReturn(ext);
            mockRedisIncrement(1L);

            StoreAddress exist = new StoreAddress();
            exist.setId(1L);
            exist.setMerchantId(999L);
            when(storeAddressMapper.selectById(1L)).thenReturn(exist);

            StoreAddress addr = new StoreAddress();
            addr.setId(1L);
            addr.setMerchantId(1L);

            BizException ex = assertThrows(BizException.class,
                    () -> merchantService.saveStoreAddress(addr));
            assertEquals(ResultCode.FORBIDDEN.getCode(), ex.getCode());
        }

        @Test
        @DisplayName("saveStoreAddress: 新增首条地址自动设为primary并同步扩展表")
        void saveStoreAddress_firstAddress_primaryAndSync() {
            MerchantExtension ext = buildExtension(1L);
            when(merchantMapper.selectById(1L)).thenReturn(ext);
            mockRedisIncrement(1L);
            when(storeAddressMapper.selectCount(any(LambdaQueryWrapper.class))).thenReturn(0L);
            when(storeAddressMapper.insert(any(StoreAddress.class))).thenAnswer(inv -> {
                StoreAddress a = inv.getArgument(0);
                a.setId(100L);
                return 1;
            });
            when(storeAddressMapper.updateById(any(StoreAddress.class))).thenReturn(1);
            when(merchantMapper.updateById(any(MerchantExtension.class))).thenReturn(1);

            StoreAddress addr = new StoreAddress();
            addr.setMerchantId(1L);
            addr.setProvince("浙江省");
            addr.setCity("杭州市");
            addr.setAddressDetail("文三路100号");
            addr.setLongitude(new BigDecimal("120.15"));
            addr.setLatitude(new BigDecimal("30.25"));

            StoreAddress result = merchantService.saveStoreAddress(addr);
            assertEquals(1, result.getIsPrimary());
        }

        @Test
        @DisplayName("deleteStoreAddress: 非本商家地址抛异常")
        void deleteStoreAddress_wrongMerchant_throws() {
            StoreAddress exist = new StoreAddress();
            exist.setId(1L);
            exist.setMerchantId(999L);
            when(storeAddressMapper.selectById(1L)).thenReturn(exist);

            BizException ex = assertThrows(BizException.class,
                    () -> merchantService.deleteStoreAddress(1L, 1L));
            assertEquals(ResultCode.FORBIDDEN.getCode(), ex.getCode());
        }

        @Test
        @DisplayName("setPrimaryAddress: 地址不存在抛异常")
        void setPrimaryAddress_notFound_throws() {
            when(storeAddressMapper.selectById(1L)).thenReturn(null);

            BizException ex = assertThrows(BizException.class,
                    () -> merchantService.setPrimaryAddress(1L, 1L));
            assertEquals(ResultCode.FORBIDDEN.getCode(), ex.getCode());
        }

        @Test
        @DisplayName("listMerchants: 默认分页参数page=1,size=20")
        void listMerchants_defaultPagination() {
            Page<MerchantExtension> page = new Page<>(1, 20);
            page.setRecords(Collections.emptyList());
            when(merchantMapper.selectPage(any(Page.class), any(LambdaQueryWrapper.class)))
                    .thenReturn(page);

            IPage<MerchantExtension> result = merchantService.listMerchants(null, null, null, null, null, null);
            assertNotNull(result);
        }

        @Test
        @DisplayName("getAddressUpdateState: 今日计数为null时返回0")
        void getAddressUpdateState_nullValue_default0() {
            MerchantExtension ext = buildExtension(1L);
            when(merchantMapper.selectById(1L)).thenReturn(ext);
            when(stringRedisTemplate.opsForValue()).thenReturn(valueOperations);
            when(valueOperations.get(anyString())).thenReturn(null);

            Map<String, Object> result = merchantService.getAddressUpdateState(1L);
            assertEquals(0L, result.get("todayUpdatedCount"));
            assertEquals(3L, result.get("remaining"));
        }

        @Test
        @DisplayName("getAddressUpdateState: 已用3次返回remaining=0")
        void getAddressUpdateState_atLimit_remaining0() {
            MerchantExtension ext = buildExtension(1L);
            when(merchantMapper.selectById(1L)).thenReturn(ext);
            when(stringRedisTemplate.opsForValue()).thenReturn(valueOperations);
            when(valueOperations.get(anyString())).thenReturn("3");

            Map<String, Object> result = merchantService.getAddressUpdateState(1L);
            assertEquals(3L, result.get("todayUpdatedCount"));
            assertEquals(0L, result.get("remaining"));
        }

        @Test
        @DisplayName("updateLastNhDate: 更新0行仅记日志不抛异常")
        void updateLastNhDate_zeroRows_noException() {
            when(merchantMapper.update(eq(null), any(LambdaUpdateWrapper.class))).thenReturn(0);

            assertDoesNotThrow(() ->
                    merchantService.updateLastNhDate(1L, LocalDate.now()));
        }

        @Test
        @DisplayName("register: 重复提交相同营业执照号抛异常")
        void register_duplicateLicense_throws() {
            MerchantExtension ext = buildExtension(1L);
            when(merchantMapper.selectById(1L)).thenReturn(ext);

            assertThrows(BizException.class,
                    () -> merchantService.register(buildDTO(1L)));
        }
    }
}