spring:
  application:
    name: lsc-platform
  datasource:
    url: jdbc:mysql://localhost:3306/lsc?useSSL=false&serverTimezone=UTC&characterEncoding=utf8mb4
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    serialization:
      write-dates-as-timestamps: false

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 8080

logging:
  level:
    com.zcls.lsc: INFO
