apiVersion: v1
kind: Secret
metadata:
  name: lsc-secrets
  namespace: lsc-system
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "Lsc@2026#Secure"
  MYSQL_PASSWORD: "Lsc@2026#Secure"
  MYSQL_USER: "root"

  REDIS_PASSWORD: "Lsc@Redis2026"

  RABBITMQ_PASSWORD: "Lsc@MQ2026"

  NACOS_PASSWORD: "Lsc@Nacos2026"

  JWT_SECRET: "Lsc2026JwtSecretKeyMustBe32BytesAtLeast!!"

  ADMIN_PASSWORD: "Admin@2026#Secure"
  AUDITOR_PASSWORD: "Auditor@2026#Secure"
  OPERATOR_PASSWORD: "Operator@2026#Secure"

  CHAIN_RPC_URL: "http://chain-rpc:8545"
  CHAIN_CONTRACT: ""
  CHAIN_PK: ""

  AI_API_KEY: ""
  AI_ENDPOINT: ""

  GRAFANA_PASSWORD: "Lsc@Grafana2026"

  XXL_JOB_TOKEN: "Lsc@XxlJob2026Token"