-- ---------------------------------------------------------------------------
-- Phase I: 灰度发布策略持久化建表脚本（MySQL 8.0+ / MariaDB 10.5+）
-- 说明：
--   1) 网关 lsc-gateway 连接哪个库？建议在运维默认的公共配置库（例如 lsc_admin）中执行，
--      或在 DBA 指定的独立 gateway 库中执行。表名以 gray_ 前缀避免与业务表冲突。
--   2) gray_policy.policy_id 是主键，保证幂等 upsert；MySQL JDBC 实现依赖
--      INSERT ... ON DUPLICATE KEY UPDATE。
--   3) rules_json / meta_json 使用 JSON 类型（或 TEXT 兼容低版本）。
--   4) gray_policy_history 使用自增 id，提供 (policy_id, ts) 复合索引；
--      历史只追加，不做 update，避免死锁。
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS gray_policy (
  policy_id              VARCHAR(128)    NOT NULL   COMMENT '业务语义化主键：order-service-v2.1-20260903',
  route_id               VARCHAR(128)    NOT NULL   COMMENT 'Gateway 路由 ID（与 application.yml 路由对应）',
  baseline_uri           VARCHAR(255)    NOT NULL   COMMENT '基线 lb://<service-id>',
  canary_uri             VARCHAR(255)    NOT NULL   COMMENT '灰度 lb://<service-id>-canary',
  canary_weight_percent  INT             NOT NULL   COMMENT '0~100 权重；0 时仅靠 rules 生效',
  rules_json             JSON            NULL       COMMENT 'List<Rule> 序列化：type/key/operator/value/extra',
  meta_json              JSON            NULL       COMMENT 'Map<String,String>：owner / ticketId / 版本号等',
  status                 VARCHAR(16)     NOT NULL   COMMENT 'ACTIVE / PAUSED / ROLLED_BACK / GRADUATED',
  created_at             DATETIME(3)     NOT NULL   COMMENT '创建时间（ms 精度）',
  updated_at             DATETIME(3)     NOT NULL   COMMENT '最后更新时间',
  updated_by             VARCHAR(64)     NULL       COMMENT '最后操作人（来自 X-Admin-User 头）',
  PRIMARY KEY (policy_id),
  KEY idx_gray_policy_route (route_id),
  KEY idx_gray_policy_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='灰度发布策略（Gateway 内存态的持久化源）';

CREATE TABLE IF NOT EXISTS gray_policy_history (
  id          BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  ts          DATETIME(3)     NOT NULL   COMMENT '发生时间',
  policy_id   VARCHAR(128)    NULL       COMMENT '策略主键（DELETE 动作后仍然保留审计）',
  operator    VARCHAR(64)     NOT NULL   COMMENT '操作人',
  action      VARCHAR(32)     NOT NULL   COMMENT 'CREATE/UPDATE/WEIGHT_CHANGE/PAUSE/RESUME/ROLLBACK/GRADUATE/DELETE',
  detail      VARCHAR(1024)   NULL       COMMENT '变化详情：weight old -> new; reason 等',
  PRIMARY KEY (id),
  KEY idx_gray_policy_history_policy (policy_id, ts DESC),
  KEY idx_gray_policy_history_ts (ts DESC),
  KEY idx_gray_policy_history_action (action)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='灰度策略变更历史（只追加，用于审计 / 故障根因追溯）';

-- ---------------------------------------------------------------------------
-- H2 适配（仅本地 / 单元测试使用；JDBC 实现内部自动用 UPDATE/INSERT 兜底 MERGE）
-- 以下脚本在 H2 模式下等价，H2 允许 DATETIME / JSON（TEXT 兼容）：
--
-- CREATE TABLE IF NOT EXISTS gray_policy (
--   policy_id VARCHAR(128) PRIMARY KEY,
--   route_id VARCHAR(128) NOT NULL,
--   baseline_uri VARCHAR(255) NOT NULL,
--   canary_uri VARCHAR(255) NOT NULL,
--   canary_weight_percent INT NOT NULL,
--   rules_json TEXT NULL,
--   meta_json TEXT NULL,
--   status VARCHAR(16) NOT NULL,
--   created_at TIMESTAMP NOT NULL,
--   updated_at TIMESTAMP NOT NULL,
--   updated_by VARCHAR(64) NULL
-- );
-- CREATE TABLE IF NOT EXISTS gray_policy_history (
--   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--   ts TIMESTAMP NOT NULL,
--   policy_id VARCHAR(128) NULL,
--   operator VARCHAR(64) NOT NULL,
--   action VARCHAR(32) NOT NULL,
--   detail VARCHAR(1024) NULL
-- );
-- CREATE INDEX IF NOT EXISTS idx_gph_policy ON gray_policy_history(policy_id, ts DESC);
-- ---------------------------------------------------------------------------
