{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: lsc-gateway
  namespace: {{ .Values.namespaceOverride | default .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: lsc-gateway
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes: [Ingress, Egress]
  ingress:
    - from: {{- toYaml .Values.networkPolicy.ingressFrom | nindent 10 }}
      ports:
        - protocol: TCP
          port: {{ .Values.service.targetPort }}
  egress:
    # allow DNS
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: UDP
          port: 53
    {{- toYaml .Values.networkPolicy.egressTo | nindent 4 }}
{{- end }}
