server:
  port: 8000
  servlet:
    encoding:
      charset: UTF-8
      force: true

spring:
  application:
    name: lsc-api-service
  jackson:
    time-zone: Asia/Shanghai
    date-format: yyyy-MM-dd HH:mm:ss

logging:
  level:
    com.lianshengtong: INFO
